# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6
game_versions_mr=1.21.6
game_versions_curse=1.21.6
parchment_version=1.21.5:2025.06.15
loader_version=0.16.13

# Mod Properties
mod_version=2.6.4
maven_group=red.jackf
archives_base_name=whereisit

# Dependencies
jackfredlib_version=0.10.7+1.21.5
yacl_version=3.7.1+1.21.6-fabric

jei_modrinth_id=xGApC30U

# JF_AUTO_UPDATE_BLOCK
fabric-api_version=0.127.1+1.21.6
architectury_version=17.0.6
modmenu_version=15.0.0-beta.3
jei_version=19.21.0.247
rei_version=19.0.805
emi_version=1.1.21+1.21.1
# JF_END_AUTO_UPDATE_BLOCK

# Publishing
prefix=[1.21.6]
release_type=release
changelog_filter=[feat],[fix],[change],[docs],[update]
mod_name=Where Is It
github_owner=JackFred2
github_repo=WhereIsIt
github_url=https://github.com/JackFred2/WhereIsIt

# Publishing Testing
#lastTag=v2.0.16
#newTag=v2.0.17